name: my_environment
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - plotly
  - nltk
  - beautifulsoup4
  - scikit-learn
  - sqlalchemy
  - csvkit
  - datetime
  - scipy
  - tsne
  - knn
  - multinomialnb
  - gaussiannb
  - xgboost
  - mlxtend
